export const GET_MOVIE_REQUSTED = 'GET_MOVIE_REQUSTED';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAILED = 'GET_MOVIE_FAILED';
export const REMOVE_MOVIE_DATA = 'REMOVE_MOVIE_DATA';